# Generated by Django 2.2.2 on 2019-07-07 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeReservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttime',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_appointment_times', to='TimeReservation.Clinic'),
        ),
        migrations.AlterField(
            model_name='appointmenttime',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointment_times', to='Accounts.Doctor'),
        ),
        migrations.AlterField(
            model_name='appointmenttime',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_appointment_times', to='Accounts.Hospital'),
        ),
        migrations.AlterField(
            model_name='appointmenttime',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointment_times', to='Accounts.Patient'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_clinics', to='Accounts.Doctor'),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_working_hours', to='TimeReservation.Clinic'),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_working_hours', to='Accounts.Doctor'),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_working_hours', to='Accounts.Hospital'),
        ),
    ]
