# Generated by Django 2.2.2 on 2019-06-15 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeReservation', '0003_auto_20190613_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmenttime',
            old_name='reserved',
            new_name='has_reserved',
        ),
        migrations.RemoveField(
            model_name='appointmenttime',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointmenttime',
            name='time',
        ),
        migrations.AddField(
            model_name='appointmenttime',
            name='date_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='appointmenttime',
            name='reservation_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='doctor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Doctor'),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='clinic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TimeReservation.Clinic'),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='hospital',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Hospital'),
        ),
        migrations.DeleteModel(
            name='Bonus',
        ),
    ]
