# Generated by Django 2.2.2 on 2019-07-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeReservation', '0003_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus',
            name='off_percent',
        ),
        migrations.AddField(
            model_name='bonus',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
