# Generated by Django 2.2.2 on 2019-06-15 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeReservation', '0004_auto_20190615_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttime',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Doctor'),
        ),
    ]
