# Generated by Django 2.2.2 on 2019-06-15 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeReservation', '0005_auto_20190615_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttime',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Patient'),
        ),
    ]
