# Generated by Django 2.2.2 on 2019-06-15 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_auto_20190612_2123'),
        ('TimeReservation', '0006_auto_20190615_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttime',
            name='clinic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='TimeReservation.Clinic'),
        ),
        migrations.AddField(
            model_name='appointmenttime',
            name='hospital',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Hospital'),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='clinic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='TimeReservation.Clinic'),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='hospital',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Hospital'),
        ),
    ]
