# Generated by Django 2.2.2 on 2019-06-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeReservation', '0007_auto_20190615_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttime',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workinghour',
            name='period',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='workinghour',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
