# Generated by Django 2.2.2 on 2019-06-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeReservation', '0008_auto_20190615_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttime',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='period',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='price',
            field=models.IntegerField(),
        ),
    ]
