# Generated by Django 2.2.2 on 2019-06-16 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeReservation', '0009_auto_20190615_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghour',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TimeReservation.Clinic'),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Hospital'),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='period',
            field=models.IntegerField(help_text='in minutes'),
        ),
    ]
