# Generated by Django 2.2.2 on 2019-06-16 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeReservation', '0010_auto_20190616_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghour',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Doctor'),
        ),
    ]
