# Generated by Django 2.2.2 on 2019-06-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeReservation', '0011_auto_20190616_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghour',
            name='day',
            field=models.CharField(choices=[('Saturday', 'شنبه'), ('Sunday', 'یکشنبه'), ('Monday', 'دوشنبه'), ('Tuesday', 'سه شنبه'), ('Wednesday', 'چهارشنبه'), ('Thursday', 'پنج شنبه'), ('Friday', 'جمعه')], max_length=8),
        ),
    ]
