# Generated by Django 2.2.2 on 2019-06-16 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeReservation', '0012_auto_20190616_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttime',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TimeReservation.Clinic'),
        ),
        migrations.AlterField(
            model_name='appointmenttime',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Doctor'),
        ),
        migrations.AlterField(
            model_name='appointmenttime',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Hospital'),
        ),
        migrations.AlterField(
            model_name='appointmenttime',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Patient'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Doctor'),
        ),
    ]
