# Generated by Django 2.2.2 on 2019-06-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeReservation', '0014_auto_20190616_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='name',
            field=models.CharField(default='Khomeini', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone_number',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='day',
            field=models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه شنبه', 'سه شنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنج شنبه', 'پنج شنبه'), ('جمعه', 'جمعه')], max_length=8),
        ),
    ]
