# Generated by Django 2.2.1 on 2019-06-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20190610_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='picture',
            field=models.ImageField(blank=True, default='Profile Pictures/Hospitals/default.png', upload_to='Profile Pictures/Hospitals/'),
        ),
    ]
