# Generated by Django 2.2.1 on 2019-06-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20190611_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='doctors',
            field=models.ManyToManyField(null=True, to='Accounts.Doctor'),
        ),
    ]
