# Generated by Django 2.2.1 on 2019-06-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_hospital_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('زن', 'زن'), ('مرد', 'مرد')], max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('زن', 'زن'), ('مرد', 'مرد')], max_length=3),
        ),
    ]
