# Generated by Django 2.2.2 on 2019-06-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_auto_20190612_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='doctors',
            field=models.ManyToManyField(null=True, related_name='hospitals', to='Accounts.Doctor'),
        ),
    ]
